<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
	<RuntimeIdentifiers>osx-arm64;osx-x64</RuntimeIdentifiers>
	 <Copyright>JustyBaseTeam</Copyright>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseLocalDb2Driver)' == 'true'">
    <ProjectReference Include="$(JustyBaseLocalDb2Project)" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalDb2Driver)' != 'true'">
    <PackageReference Include="JustyBase.Db2" Version="$(JustyBaseDb2PackageVersion)" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\JustyBase.PluginBase\JustyBase.PluginBase.csproj">
			<Private>false</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
		<ProjectReference Include="..\..\JustyBase.PluginCommon\JustyBase.PluginCommon.csproj">
			<Private>false</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>
</Project>
