global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Controls.Presenters;
global using Avalonia.Input;
global using Avalonia.Interactivity;
global using Avalonia.Layout;
global using Avalonia.Media;
global using Avalonia.Styling;
global using Avalonia.Threading;
global using AvaloniaEdit;
global using AvaloniaEdit.CodeCompletion;
global using AvaloniaEdit.Document;
global using AvaloniaEdit.Editing;
global using AvaloniaEdit.Folding;
global using AvaloniaEdit.Highlighting;
global using Avalonia.Platform.Storage;
global using AvaloniaEdit.Rendering;
global using AvaloniaEdit.Snippets;
global using ModifierKeys = Avalonia.Input.KeyModifiers;
global using TextCompositionEventArgs = Avalonia.Input.TextInputEventArgs;
global using CommonTextEventArgs = Avalonia.Input.TextInputEventArgs;
global using RoutingStrategy = Avalonia.Interactivity.RoutingStrategies;
global using CommonBrush = Avalonia.Media.IBrush;
global using CommonImage = Avalonia.Media.IImage;
global using TextDocument = AvaloniaEdit.Document.TextDocument;
