<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <!--<EnableDynamicLoading>true</EnableDynamicLoading>-->
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\JustyBase.PluginBase\JustyBase.PluginBase.csproj">
			<Private>false</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup Condition="'$(UseLocalJustyBaseLibraries)' == 'true'">
		<ProjectReference Include="$(JustyBaseLocalNetezzaProject)" />
		<ProjectReference Include="$(JustyBaseLocalNetezzaDdlProject)" />
		<ProjectReference Include="$(JustyBaseLocalNetezzaCatalogSqlProject)" />
		<ProjectReference Include="$(JustyBaseLocalImportExportProject)" />
	</ItemGroup>
	<ItemGroup Condition="'$(UseLocalJustyBaseLibraries)' != 'true'">
		<PackageReference Include="JustyBase.Netezza" Version="$(JustyBaseNetezzaLibsPackageVersion)" />
		<PackageReference Include="JustyBase.NetezzaDdl" Version="$(JustyBaseNetezzaLibsPackageVersion)" />
		<PackageReference Include="JustyBase.NetezzaCatalogSql" Version="$(JustyBaseNetezzaLibsPackageVersion)" />
		<PackageReference Include="JustyBase.ImportExport" Version="$(JustyBaseNetezzaLibsPackageVersion)" />
	</ItemGroup>
</Project>
